#!/usr/bin/env bash

function print_string_array {
	local -a ARR=( "$@" )
	echo -n "["
	if (( "${#ARR[@]}" > 1 )); then
		printf "\"%s\", " "${ARR[@]:0:${#ARR[@]}-1}"
	fi
	if (( "${#ARR[@]}" )); then
		echo -n "\"${ARR[*]:${#ARR[@]}-1:1}\""
	fi
	echo "]"
}

declare HAS_LVPATH=
declare LVPATH=""
declare -a OTHER_FLAGS=()
declare -a NONFLAG_ARGS=()

while (( "$#" )); do
	case "$1" in
		-lvpath)
			HAS_LVPATH=1
			LVPATH="$2"
			shift 2
			;;
		-*)
			OTHER_FLAGS+=( "$1" )
			shift
			;;
		*)
			NONFLAG_ARGS+=( "$1" )
			shift
			;;
	esac
done

cat <<EOF
{
EOF
if (( HAS_LVPATH )); then
	cat <<EOF
  "labview-executable": "$LVPATH",
EOF
fi
cat <<EOF
  "other-flags": $(print_string_array "${OTHER_FLAGS[@]}"),
  "nonflag-args": $(print_string_array "${NONFLAG_ARGS[@]}")
}
EOF
